A lot of improvementes and compatibility with newer versions of Python
polyswarm/django-searchable-select pull request #1
Opened 2022-02-25 22:22 UTC by mrsarm

2022-02-28 14:09 UTC, mrtizmoatwork commented on README.rst
> +Anf the mapping of the table where you have all the possible tags:
"Anf" -> "And"

2022-02-28 14:13 UTC, mrtizmoatwork requested changes
one minor spelling change, the rest is good to go

2022-03-01 13:41 UTC, mrtizmoatwork approved these changes, later dismissed
looking good

2022-03-01 13:50 UTC, mrsarm commented
@mrtizmoatwork please could you approve again? Because this was a fork of a project that I started to edit outside the `polyswarm` GH account, my commits were not signed with my GPG Key, now I rebased the last commit with my signature.

2022-03-01 14:21 UTC, mrtizmoatwork approved these changes, later dismissed
ok

2022-03-01 15:06 UTC, mrtizmoatwork approved these changes
ok

2022-03-01 15:07 UTC, merged